ecbuild:
  build: YES
  repo: GEOS-ESM
  version: geos/v1.0.5

esma_cmake:
  build: YES
  repo: GEOS-ESM
  version: develop

cmakemodules:
  build: YES
  repo: NOAA-EMC
  version: develop

hdf5:
  build: YES
  version: 1.10.6
  shared: YES
  enable_szip: NO
  enable_zlib: YES

netcdf:
  build: YES
  shared: YES
  enable_pnetcdf: NO
  version_c: 4.7.4
  version_f: 4.5.3
  version_cxx: 4.3.1

esmf:
  build: YES
  version: 8_1_0_beta_snapshot_27
  shared: YES
  enable_pnetcdf: NO
  debug: NO

gftl_shared:
  build: YES
  repo: Goddard-Fortran-Ecosystem
  version: v1.0.7

pflogger:
  build: YES
  repo: Goddard-Fortran-Ecosystem
  version: v1.4.2

pfunit:
  build: YES
  repo: Goddard-Fortran-Ecosystem
  version: v4.1.8

yafyaml:
  build: YES
  repo: Goddard-Fortran-Ecosystem
  version: v0.3.3

flap:
  build: YES
  repo: mathomp4
  version: geos/v1.9.0

mapl:
  build: YES
  repo: GEOS-ESM
  version: v2.4.0
